pruebaan/config/routes.rb
Rails.application.routes.draw do
  get 'people/index'
  get 'people/new'
  get 'people/show'
  get 'people/edit'
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

pruebaan/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pruebaan/app/models/document.rb
class Document < ApplicationRecord
 has_many :people
end

pruebaan/app/models/person.rb
class Person < ApplicationRecord
    belongs_to :document
    belongs_to :role
end

pruebaan/app/models/role.rb
class Role < ApplicationRecord
   has_many :people
end

pruebaan/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

pruebaan/app/controllers/people_controller.rb
class PeopleController < ApplicationController

    def index
      @people = Person.all
    end
  
    def new
      @person = Person.new
    end
  
    def show
      @person = Person.find(params[:id])
    end
  
    def create
      @person = Person.new(person_params)
      if @person.save
        redirect_to person_path(@person)
      else
        render :new
      end
    end
  
    def edit
      @person = Person.find(params[:id])
    end
  
    def update
      @person = Person.find(params[:id])
      if @person.update(person_params)
        redirect_to person_path(@person)
      else
        render :edit
      end
    end
  
    def destroy
      @person = Person.find(params[:id])
      if @person.destroy
      redirect_to people_path
      else 
         render :new
      end   
    end
  
    private
  
    def person_params
      params.require(:person).permit(:identificacion, :first_name , :second_name, :first_last_name, :second_last_name, :document_id, :role_id )
    end
  end

pruebaan/app/helpers/application_helper.rb
module ApplicationHelper
end

pruebaan/app/helpers/people_helper.rb
module PeopleHelper
end

pruebaan/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pruebaan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <main class ="container">
    <section class ="row">
    <aside class ="col-md-4">
    <div =class="list-group">
    <a href="#" class ="list.group-item list-group-item-action active" aria-current="true">
   
    </a>
    <a href="<%= new_person_path%> "class="list-group-item list-group-item-action>"">registrar</a> 
  
    <a href="<%=people_index_path%> "class="list-group-item list-group-item-action>">lista</a>
 
    </div>
    </aside>
   
    <article class = "col-md-8">
     <%= yield %>
    </article>

    </section>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

  </body>
</html>

pruebaan/app/views/people/_form.html.erb
<%= simple_form_for @person do |f| %>
  <%= f.association :document, label_method: :document_type %>
    <%= f.input :identificacion %>
    <%= f.input :first_name %>
    <%= f.input :second_name%>
    <%= f.input :first_last_name %>
    <%= f.input :second_last_name %>
    <%= f.association :role, label_method: :role_name %>
    <%= f.button :submit %>
   
  <% end %>

pruebaan/app/views/people/_person.html.erb
<tr>
<th scope="row"><%= person.id %></th>
<td><%= person.document.document_type%> </td>
<th><%= link_to person.identificacion, person_path(person.id) %></th>
<th><%= person.first_name %></th>
<th><%= person.second_name %></th>
<th><%= person.first_last_name%></th>
<th><%= person.second_last_name  %></th>
<td><%= person.role.role_name%> </td>
</tr>

pruebaan/app/views/people/edit.html.erb
<h1>People#edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>
<%= render 'form' %>
ashkdgasjhdkajshdajkshdajkshdlasd

pruebaan/app/views/people/index.html.erb
<h1>People#index</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">tipo de documento</th>
      <th scope="col">identificacion</th>
      <th scope="col">primer nombre</th>
      <th scope="col">segundo nombre</th>
      <th scope="col">primer apellido</th>
      <th scope="col">segundo apellido</th>
      <th scope="col">rol</th>
    </tr>
  </thead>
  <tbody>
    <%= render @people%>

  </tbody>
</table>

pruebaan/app/views/people/new.html.erb
<%= render 'form' %>

pruebaan/app/views/people/show.html.erb
<h1>People#show</h1>
<p>Find me in app/views/people/show.html.erb</p>
<dl>
<dt>identidicacion</dt>
<dd><%=@person.identificacion %></dd>
<dt>primer nombre</dt>
<dd><%=@person.first_name %></dd>
<dt>segundo nombre</dt>
<dd><%=@person.second_name %></dd>
<dt>primer apellido</dt>
<dd><%=@person.first_last_name %></dd>
<dt>segundo apellido</dt>
<dd><%=@person.second_last_name  %></dd>
</dl>
<a href="<%= edit_person_path%> " >editar</a> |

<a href="<%=people_index_path%>" >lista</a> |